package voyage.vol.model;

<<<<<<< HEAD
import javax.persistence.*;

@Entity
public class CompagnieAerienneVol {
	private String numero;
	private int version;
	private CompagnieAerienne compagnieAerienne;
	private Vol vol;
=======
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Version;




@Entity
@Table(name = "compagnie_aerienne_vol")
@IdClass(CompagnieAerienneVolId.class)
public class CompagnieAerienneVol {
	
	private CompagnieAerienne compagnieAerienne;
	private Vol vol;
	private String numero;
	private int version;
>>>>>>> fce536c217eef67091b2c7025b3def78c1b5ad72
	
	
	public CompagnieAerienneVol() {
		super();
	}
<<<<<<< HEAD
	public CompagnieAerienneVol(String numero) {
		this.numero = numero;
	}
	
	public CompagnieAerienneVol(String numero, CompagnieAerienne compagnieAerienne, Vol vol) {
		this.numero = numero;
		this.compagnieAerienne = compagnieAerienne;
		this.vol = vol;
	}
	
	@Id
	public String getNumero() {
		return numero;
	}
	
	public void setNumero(String numero) {
		this.numero = numero;
	}
	
=======

	
	@Id
	@ManyToOne
	@JoinColumn(name = "compagnie_aerienne_id")
	public CompagnieAerienne getCompagnieAerienne() {
		return compagnieAerienne;
	}

	public void setCompagnieAerienne(CompagnieAerienne compagnieAerienne) {
		this.compagnieAerienne = compagnieAerienne;
	}

	@Id
	@ManyToOne
	@JoinColumn(name = "vol_id")
	public Vol getVol() {
		return vol;
	}

	public void setVol(Vol vol) {
		this.vol = vol;
	}

	// TODO Make an AutoGenerated number
	@Column(length=100, nullable=false)
	public String getNumero() {
		return numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

>>>>>>> fce536c217eef67091b2c7025b3def78c1b5ad72
	@Version
	public int getVersion() {
		return version;
	}
<<<<<<< HEAD
=======

>>>>>>> fce536c217eef67091b2c7025b3def78c1b5ad72
	public void setVersion(int version) {
		this.version = version;
	}
	
<<<<<<< HEAD
	@ManyToOne
	public CompagnieAerienne getCompagnieAerienne() {
		return compagnieAerienne;
	}
	
	public void setCompagnieAerienne(CompagnieAerienne compagnieAerienne) {
		this.compagnieAerienne = compagnieAerienne;
	}
	
	@ManyToOne
	public Vol getVol() {
		return vol;
	}
	
	public void setVol(Vol vol) {
		this.vol = vol;
	}
	
	
=======
	
	
	

>>>>>>> fce536c217eef67091b2c7025b3def78c1b5ad72
}
